name: Build ESP32-S3 QuickJS Static Library

on:
  pull_request:
    paths:
      - '**'
      - '!.gitignore'
      - '!LICENSE'
      - '!TODO'
      - '!doc/**'
      - '!examples/**'
      - '.github/workflows/build.yml'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 系统来运行构建

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        pip3 install -r requirements.txt  # 安装 QuickJS 编译的依赖
        mkdir -p ~/esp
        cd ~/esp
        git clone -b v5.4 --recursive https://github.com/espressif/esp-idf.git
        cd ~/esp/esp-idf
        ./install.sh all
        . $HOME/esp/esp-idf/export.sh
        alias get_idf='. $HOME/esp/esp-idf/export.sh'
        source ~/.bashrc

    - name: Compile QuickJS for ESP32-S3
      run: |
        cd path_to_your_quickjs  # 进入 QuickJS 源码目录
        make CROSS_PREFIX=xtensa-esp32-elf- -D__STDC_NO_ATOMICS__=1  # 运行 QuickJS 编译命令，这里假设你有适配 ESP32-S3 的 makefile

    - name: Package static library
      run: |
        mkdir -p build_output
        cp path_to_quickjs_lib/libquickjs.a build_output/libquickjs.a  # 复制静态链接库到输出文件夹

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build_output/libquickjs.a # 指定需要发布的文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub token 来创建 release
