name: Build ESP32-S3 QuickJS Static Library

on:
  pull_request:
    paths:
      - '**'
      - '!.gitignore'
      - '!LICENSE'
      - '!TODO'
      - '!doc/**'
      - '!examples/**'
      - '.github/workflows/build.yml'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 系统来运行构建

    steps:
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install jq git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        release_info=$(curl -s https://api.github.com/repos/espressif/crosstool-NG/releases/latest)
        tag_name=$(echo "$release_info" | jq -r '.tag_name')
        #tag_name="esp-14.2.0_20241119"
        ESP_GNU_TOOLCHAIN_VER=$(echo "${tag_name#*-}"  )
        download_url="https://github.com/espressif/crosstool-NG/releases/download/esp-${ESP_GNU_TOOLCHAIN_VER}/xtensa-esp-elf-${ESP_GNU_TOOLCHAIN_VER}-x86_64-linux-gnu.tar.gz"
        echo ${download_url}
        #curl -L "$download_url" -o xtensa-esp-elf-x86_64-linux-gnu.tar.gz

